### ISSUE TITLE
Establish this repo as a place for generic templates.

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/containers-quickstarts#155] opened 2018-12-14 15:11 UTC

**Comment by pabrahamsson** [comment] 2019-02-18 17:43
@etsauer can you please add some more details to this? Are there specific templates you're looking for? How would we determine this issue to be resolved?

**Comment by pcarney8** [comment] 2019-03-25 18:45
@pabrahamsson see #194 as one example

**Comment by etsauer** [comment] 2019-03-25 23:54
@pcarney8 @pabrahamsson based on recent conversations regarding https://github.com/rht-labs/openshift-templates, i'm wondering if we still want to do this, or whether we should consider migrating this repo into the CoP instead (or establishing a new one dedicated to just template examples)

**Comment by sherl0cks** [comment] 2019-03-26 01:15
@pcarney8 @etsauer I say we would pull the bandaid off and [transfer the repo](https://help.github.com/en/articles/transferring-a-repository). 

I just did a short test that I believe proves this is a safe function. The only dependency that I'm aware of is various labs ci/cd releases, and customer forks of those releases, that use the github raw API to consume templates, like in [this example](https://github.com/rht-labs/labs-ci-cd/blob/v3.11.5/inventory/host_vars/projects-and-policies.yml#L37). 

Since we transferred the Open Practice Library repositories, we can test out the behavior of the raw API. It seems github continues to serve the raw content of the repository at the time it was transferred. For example https://raw.githubusercontent.com/rht-labs/practice-library/master/README.md vs https://raw.githubusercontent.com/openpracticelibrary/openpracticelibrary/master/README.md. There does not appear to be any redirects going on for new content. For example https://raw.githubusercontent.com/rht-labs/practice-library/master/content/practice/design-sprint.md vs https://raw.githubusercontent.com/openpracticelibrary/openpracticelibrary/master/content/practice/design-sprint.md. This behavior seems ideal. We will not break existing users and we can update the new code to point to new versions as appropriate.

Since github does not allow me to link teams, @oybed @InfoSec812 @makentenza @springdo @jacobsee @tylerauerbeck @syvanen @rdebeasi @haithamshahin333 does anyone have strong opinions to the contrary on the above? We should look to make this move by end of week.

**Comment by tylerauerbeck** [comment] 2019-03-26 01:26
@sherl0cks @pcarney8 @etsauer 

Is moving the repo in reference of moving rht-labs/openshift-templates into the CoP? If that's the case I think I'm good with it. I think we'll just want to be clear about the purposes of both of these repos now (i.e. what belongs in quickstarts versus Openshift-templates). If I'm completely wrong here though, feel free to correct me.

**Comment by sherl0cks** [comment] 2019-03-26 01:44
This is indeed the intent @tylerauerbeck. Eric did a good job documenting exactly your question: https://github.com/redhat-cop/containers-quickstarts/blob/master/CONTRIBUTING.md#contribution-guide.

FWIW - we'll need to update that doc to point to the new repo.

**Comment by makentenza** [comment] 2019-03-26 13:01
@sherl0cks @pcarney8 @etsauer 

I can't see any reason why we shouldn't keep all the templates we use for residencies under the CoP repositories, so this is fine to me.

That said, I think we have some still some issues when it comes to these templates customization for some customers, and as we can't the template generic enough to cover all these cases we are ending forking this repo to the residency repo and work from that. This could be potentially solved using jinja templates that are processed as part of the applier runtime, but we are not supporting that yet, so we could add more custom configuration to those templates, but this is probably a topic for another conversation.

The other concern I've got (and this is not only related to CoP repos) is the CI. We don't have a strong CI or even any CI in place for this, and we normally end up with a broken Labs CI/CD from time to time. I think you guys have already talked about this many times, but we should put a strong CI in place here. We need to understand the CoP is a community-driven effort that has no commitments with Customers, but we as Labs have strong commitments and we use these repositories to generate economic impact back to Open Innovation Labs.

Another topic we have been discussing for a while is the optimistic merge approach. We got complains about the slow and difficult feedback when contributing to our own repositories when they are "hosted" under the CoP. I think we need to solve this as well. We need to put a CI in place first, but at the same time, we should agree on how the code is merged. For other repositories, we have put simple rules like "no PRs will be accepted if they don't solve any existing issue(s)", or "we will automatically merge the code if solves an existing issue and it pass the CI process" so we don't get stuck on approving a PR because there is a typo in the README.... 

These are just some thoughts, but maybe we should have a more inclusive conversation here over BJ or other channel and get back with an agreement from all the sides on how we are going to work on this going forward and how we can make this work more reliable.

**Comment by springdo** [comment] 2019-03-26 15:02
Yeah I agree with your thoughts there @makentenza. Esp that these repos are often ref'd by our customers and so can be painful to explain a change upstream while mid residency....

Prior to labs-ci-cd being broken down into a million repos, the model was monolithic but simple. It meant that customers could fork it, tweak to their specific needs and if there were new tools etc, they could be pushed back upstream. This is becoming less compelling for customers now as labs-ci-cd refers to about 4 million other repositories, each with multiple version tags for the components being used! Making changes to those dependencies is a faff and I've noticed our customers are no longer interested in taking the time to push back upstream.

[Optimistic merging](http://hintjens.com/blog:106) and proper tagging could solve these issues, but everyone would have to agree that is the way we want to version control the content. The issue is that people are not always available to constantly accept PRs into these repos and queues form (A quick glance shows a PR in this repo open since 9 Dec 2016....). 
Improving the quality of a PR should be done by the reviewer if they feel strongly about something. If a PR provides value to a consultant, developer or customer - it should just be merged. Tweaks and improvements can be added by those who feel obliged to do so. As long as your CI is passing and your solving issues, merge. If this happens then I am OK with moving things further into the CoP banner

**Comment by tylerauerbeck** [comment] 2019-03-26 15:36
@springdo @makentenza @pcarney8 @sherl0cks I think there's a conversation to be had about how we've broken apart labs-ci-cd, but I think there's probably a better place to do this than this issue. Maybe we either take this to the labs-ci-cd repo or set up some time to discuss this at a later time.

With that being said, I do agree with better CI/CD a lot of our concerns probably go away. This is something I know the CoP has already been working on and has actually been talked through recently, so I don't think we need to beat this topic to death. But I do think it will help with easier merges. My concern here is that optimistic merges turn to -- merge everything, deal with cleanup later. I think there's still room for constructive feedback and don't want that to be lost in this whole process. I don't think anyone's saying that (or pushing for), but I just wanted to make sure we still account for/ accept this in our repos.

**Comment by pabrahamsson** [comment] 2019-03-29 14:59
This issue was discussed during the CoP call today and the consensus was to transfer [openshift-templates](https://github.com/rht-labs/openshift-templates) to the redhat-cop org, see [#15](https://github.com/rht-labs/openshift-templates/issues/15)

**Comment by pabrahamsson** [comment] 2019-07-02 15:07
We now have [openshift-templates](/redhat-cop/openshift-templates) under the CoP organization, closing.

**Closed by pabrahamsson** 2019-07-02 15:07 UTC
Labels: enhancement
