### ISSUE TITLE
Jenkins-Agent-Zap Error

### ISSUE THREAD

**Issue by vijaycs199** [redhat-cop/containers-quickstarts#548] opened 2022-01-20 07:53 UTC
When we are trying to build an image from the jenkins-agent-zap, we are getting the below error.

Step 11/13 : RUN curl -sL https://github.com/zaproxy/zaproxy/releases/download/v${ZAPROXY_VERSION}/ZAP_${ZAPROXY_VERSION}_Linux.tar.gz | tar zx --strip-components=1 && curl -sL https://bitbucket.org/meszarv/webswing/get/${WEBSWING_VERSION}.tar.gz | tar zx --strip-components=1 -C webswing && rm -rf webswing/demo && touch AcceptedLicense && git clone --depth 1 --branch v${ZAPROXY_VERSION} https://github.com/zaproxy/zaproxy /tmp/zaproxy && rsync -av /tmp/zaproxy/docker/{policies,scripts,zap*} /zap/ && rsync -av /tmp/zaproxy/docker/policies /var/lib/jenkins/.ZAP/ && rsync -av /tmp/zaproxy/docker/webswing.config /zap/webswing/webswing.config && rm -rf /tmp/zaproxy && touch /.dockerenv && chown root:root /zap -R && chown root:root -R /var/lib/jenkins && chmod 777 /var/lib/jenkins -R && chmod 777 /zap -R
---> Running in 6fac21dfee38

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

Because of this error, we got stuck to create an docker image. Quickest reply is helpful for u.

**Comment by garethahealy** [comment] 2022-01-20 09:24
have just cloned and built the zap image without any issues. The URLs mentioned in step 11, can you access them? or are you behind a proxy/firewall etc?

**Comment by vijaycs199** [comment] 2022-01-20 10:20
I have cloned the repository to my local and pushed that to our bitbucket repository. From openshift console, i used the bitbucket url to do the build.  At that time only it is showing the above error.

I can access that github and bitbucket url's for ZAP v2.9.0 and webswing from the servers. There is no proxy.

Seems we are having this line 

tar zx --strip-components=1

and tar zx --strip-components=1 -C webswing

Please check and do the needful.

**Comment by vijaycs199** [comment] 2022-01-20 10:22
Also i have used wget --no-check-certificate command to download the files instead of curl. If i use curl I am getting below error

Step 11/15 : RUN curl -sL https://github.com/zaproxy/zaproxy/releases/download/v${ZAPROXY_VERSION}/ZAP_${ZAPROXY_VERSION}_Linux.tar.gz  | tar xvf --strip-components=1 &&     curl -sL https://bitbucket.org/meszarv/webswing/get/${WEBSWING_VERSION}.tar.gz  | tar xvf --strip-components=1 -C webswing &&     rm -rf webswing/demo &&     touch AcceptedLicense &&     git clone --depth 1 --branch v${ZAPROXY_VERSION} https://github.com/zaproxy/zaproxy  /tmp/zaproxy &&     rsync -av /tmp/zaproxy/docker/{policies,scripts,zap*} /zap/ &&     rsync -av /tmp/zaproxy/docker/policies /var/lib/jenkins/.ZAP/ &&     rsync -av /tmp/zaproxy/docker/webswing.config /zap/webswing/webswing.config &&     rm -rf /tmp/zaproxy &&     touch /.dockerenv &&     chown root:root /zap -R &&     chown root:root -R /var/lib/jenkins &&     chmod 777 /var/lib/jenkins -R &&     chmod 777 /zap -R
 ---> Running in 9b8569546eb8

tar: --strip-components=1: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
Removing intermediate container 9b8569546eb8
error: build error: The command '/bin/sh -c curl -sL https://github.com/zaproxy/zaproxy/releases/download/v${ZAPROXY_VERSION}/ZAP_${ZAPROXY_VERSION}_Linux.tar.gz  | tar xvf --strip-components=1 &&     curl -sL https://bitbucket.org/meszarv/webswing/get/${WEBSWING_VERSION}.tar.gz  | tar xvf --strip-components=1 -C webswing &&     rm -rf webswing/demo &&     touch AcceptedLicense &&     git clone --depth 1 --branch v${ZAPROXY_VERSION} https://github.com/zaproxy/zaproxy  /tmp/zaproxy &&     rsync -av /tmp/zaproxy/docker/{policies,scripts,zap*} /zap/ &&     rsync -av /tmp/zaproxy/docker/policies /var/lib/jenkins/.ZAP/ &&     rsync -av /tmp/zaproxy/docker/webswing.config /zap/webswing/webswing.config &&     rm -rf /tmp/zaproxy &&     touch /.dockerenv &&     chown root:root /zap -R &&     chown root:root -R /var/lib/jenkins &&     chmod 777 /var/lib/jenkins -R &&     chmod 777 /zap -R' returned a non-zero code: 2

**Comment by vijaycs199** [comment] 2022-01-20 10:28
If i use the original command getting the below error



Step 11/15 : RUN curl -sL https://github.com/zaproxy/zaproxy/releases/download/v${ZAPROXY_VERSION}/ZAP_${ZAPROXY_VERSION}_Linux.tar.gz  \| tar zx --strip-components=1 &&     curl -sL https://bitbucket.org/meszarv/webswing/get/${WEBSWING_VERSION}.tar.gz  \| tar zx --strip-components=1 -C webswing &&     rm -rf webswing/demo &&     touch AcceptedLicense &&     git clone --depth 1 --branch v${ZAPROXY_VERSION} https://github.com/zaproxy/zaproxy  /tmp/zaproxy &&     rsync -av /tmp/zaproxy/docker/{policies,scripts,zap*} /zap/ &&     rsync -av /tmp/zaproxy/docker/policies /var/lib/jenkins/.ZAP/ &&     rsync -av /tmp/zaproxy/docker/webswing.config /zap/webswing/webswing.config &&     rm -rf /tmp/zaproxy &&     touch /.dockerenv &&     chown root:root /zap -R &&     chown root:root -R /var/lib/jenkins &&     chmod 777 /var/lib/jenkins -R &&     chmod 777 /zap -R
--
  | ---> Running in c2cea8a2262b
  |  
  |  
  | gzip: stdin: unexpected end of file
  | tar: Child returned status 1
  | tar: Error is not recoverable: exiting now
  | Removing intermediate container c2cea8a2262b
  | error: build error: The command '/bin/sh -c curl -sL https://github.com/zaproxy/zaproxy/releases/download/v${ZAPROXY_VERSION}/ZAP_${ZAPROXY_VERSION}_Linux.tar.gz  \| tar zx --strip-components=1 &&     curl -sL https://bitbucket.org/meszarv/webswing/get/${WEBSWING_VERSION}.tar.gz  \| tar zx --strip-components=1 -C webswing &&     rm -rf webswing/demo &&     touch AcceptedLicense &&     git clone --depth 1 --branch v${ZAPROXY_VERSION} https://github.com/zaproxy/zaproxy  /tmp/zaproxy &&     rsync -av /tmp/zaproxy/docker/{policies,scripts,zap*} /zap/ &&     rsync -av /tmp/zaproxy/docker/policies /var/lib/jenkins/.ZAP/ &&     rsync -av /tmp/zaproxy/docker/webswing.config /zap/webswing/webswing.config &&     rm -rf /tmp/zaproxy &&     touch /.dockerenv &&     chown root:root /zap -R &&     chown root:root -R /var/lib/jenkins &&     chmod 777 /var/lib/jenkins -R &&     chmod 777 /zap -R' returned a non-zero code: 2

**Comment by garethahealy** [comment] 2022-01-20 10:36
that error is saying "tar didnt get given a file to untar", if the cURL command is failing due to certificates, then it is not downloading the tar file.

as the certificate is failing for github.com, this is an environmental problem on your end, so nothing we can do.

**Comment by garethahealy** [comment] 2022-01-20 10:45
https://www.google.com/search?q=wget+pipe+to+tar&oq=wget+pipe+&aqs=chrome.0.0i512l2j69i57j0i512l6.3985j0j7&sourceid=chrome&ie=UTF-8

**Comment by vijaycs199** [comment] 2022-01-26 17:12
Thanks for your help to resolve the issue. Currently I have integrated this new repository to our groovy pipeline. After added the below code into our groovy pipeline script, getting error and at last the piepline got failed. Below is the code i have added

sh '''
          /zap/zap-baseline.py -r index.html -t http://<some website url> || return_code=$?
          echo "exit value was  - " $return_code
      '''
  }
  post {
    always {
      // publish html
      publishHTML target: [
          allowMissing: false,
          alwaysLinkToLastBuild: false,
          keepAll: true,
          reportDir: '/zap/wrk',
          reportFiles: 'index.html',
          reportName: 'OWASP Zed Attack Proxy'
        ]


The error screenshot is attached:

![image](https://user-images.githubusercontent.com/56600802/151212525-30385356-ed24-4ec2-93ee-044708d5086f.png)

**Comment by eformat** [comment] 2022-01-27 00:53
Hi @vijaycs199 .. i attach a recent jenkins / successful run using this image for comparison:

![Screenshot from 2022-01-27 10-52-53](https://user-images.githubusercontent.com/712608/151271595-4c318985-cadf-4eae-9569-fc74c6aa653d.png)

seems i get the output "_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created." where you get an error .. is this permissions related perhaps. Are you running with anyuid SCC or such ? i am not running any special privileges.

If it helps the code i'm running is part of some training we run - you can see it here to compare - https://rht-labs.com/tech-exercise/#/3-revenge-of-the-automated-testing/6a-jenkins

**Comment by vijaycs199** [comment] 2022-01-27 02:39
I do understand and you are adding the ZAP script seperately in Jenkinsfile of the application which you are running from Jenkins. But we are running pipeline groovy script to do the stages of the pipeline.

Do i need to add the script seperately in application jenkinsfile or is it okay with the pipeline groovy script?

**Comment by garethahealy** [comment] 2022-03-31 09:57
closing as the issue is user-related.

**Closed by garethahealy** 2022-03-31 09:57 UTC
Labels: question
